version: '3'
services:
  web:
    image: oghaffar/practice:1.0
    deploy:
      replicas: 8
    ports:
      - "4567:4567"
    networks:
      - myNetwork

  db:
    image: postgres:9.4
    restart: always
#    volumes:
#      - db-volume:/var/lib/postgresql/data
    networks:
      - myNetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: oghaffar
      POSTGRES_PASSWORD: notASecret
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  myNetwork:

#volumes:
#  db-volume: