version: '3'
services:
  db:
    image: postgres:9.4
#    networks:
#      - myNetwork
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: oghaffar
      POSTGRES_PASSWORD: notASecret
    deploy:
      placement:
        constraints: [node.role == manager]

#networks:
#  myNetwork:
